# Generated by Django 3.2.8 on 2021-10-27 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_auto_20211027_1524'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'permissions': [('order_cancel', 'Can cancel order')]},
        ),
    ]
